name: flutter_moyasar
description: moyasar payment package for flutter
version: 0.0.1
homepage: https://github.com/farhioussama1969/flutter_moyasar.git

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6
  webview_flutter: ^3.0.4
  flutter_svg: ^1.0.0
  loading_animation_widget: ^1.2.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:

